# Generated by Django 2.1.1 on 2018-09-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_nome_computador', max_length=60)),
            ],
            options={
                'db_table': 'computadores',
                'managed': True,
            },
        ),
    ]
