# Generated by Django 2.1.1 on 2018-09-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_column='dt_cadastro'),
        ),
    ]
