# Generated by Django 2.1.1 on 2018-09-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latam', '0002_auto_20180831_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(db_column='tx_nome_computador', max_length=244, null=True),
        ),
    ]
